from __future__ import annotations

import logging
from typing import Any, Optional

from fastapi import APIRouter, Request, Response, status
from fastapi.responses import JSONResponse, PlainTextResponse

from app.core.config import settings
from app.domain.models.normalized_message import NormalizedMessage

router = APIRouter()
logger = logging.getLogger(__name__)


def _safe_str(value: Any) -> str:
    if value is None:
        return ""
    return str(value).strip()


def _extract_text_from_message(message: dict[str, Any]) -> str:
    """
    Tries to extract user text from Meta message payload.
    Keeps logic conservative and safe.
    """
    text = _safe_str(message.get("text"))
    if text:
        return text

    # Instagram changes-style sometimes nests text deeper
    text_obj = message.get("text")
    if isinstance(text_obj, dict):
        body = _safe_str(text_obj.get("body"))
        if body:
            return body

    return ""


def _is_echo_or_self_message(messaging_event: dict[str, Any]) -> bool:
    """
    Ignore messages generated by the page/app itself.
    """
    message = messaging_event.get("message") or {}

    if message.get("is_echo") is True:
        return True

    if messaging_event.get("sender", {}).get("id") == messaging_event.get("recipient", {}).get("id"):
        return True

    return False


def _parse_facebook(payload: dict[str, Any]) -> Optional[NormalizedMessage]:
    for entry in payload.get("entry", []):
        for event in entry.get("messaging", []):
            if _is_echo_or_self_message(event):
                continue

            message = event.get("message") or {}
            text = _extract_text_from_message(message)

            if not text:
                continue

            sender_id = _safe_str(event.get("sender", {}).get("id"))
            recipient_id = _safe_str(event.get("recipient", {}).get("id"))
            mid = _safe_str(message.get("mid"))

            if not sender_id:
                continue

            return NormalizedMessage(
                platform="facebook",
                sender_id=sender_id,
                recipient_id=recipient_id,
                message_id=mid or None,
                user_message=text,
                raw_payload=payload,
            )

    return None


def _parse_instagram_changes_style(payload: dict[str, Any]) -> Optional[NormalizedMessage]:
    """
    Instagram webhook often comes as:
    entry[].changes[].value.messages[]
    """
    for entry in payload.get("entry", []):
        for change in entry.get("changes", []):
            value = change.get("value") or {}

            messages = value.get("messages") or []
            contacts = value.get("contacts") or []
            metadata = value.get("metadata") or {}

            if not messages:
                continue

            contact_wa_id = ""
            if contacts and isinstance(contacts, list):
                contact_wa_id = _safe_str((contacts[0] or {}).get("wa_id"))

            for msg in messages:
                text = ""

                # Common nested structure
                msg_text = msg.get("text")
                if isinstance(msg_text, dict):
                    text = _safe_str(msg_text.get("body"))
                else:
                    text = _safe_str(msg.get("text"))

                if not text:
                    continue

                sender_id = _safe_str(msg.get("from")) or contact_wa_id
                recipient_id = _safe_str(metadata.get("phone_number_id")) or _safe_str(metadata.get("display_phone_number"))
                mid = _safe_str(msg.get("id"))

                if not sender_id:
                    continue

                return NormalizedMessage(
                    platform="instagram",
                    sender_id=sender_id,
                    recipient_id=recipient_id,
                    message_id=mid or None,
                    user_message=text,
                    raw_payload=payload,
                )

    return None


def _parse_instagram_messaging_style(payload: dict[str, Any]) -> Optional[NormalizedMessage]:
    """
    Instagram can also arrive in messaging-style payload:
    entry[].messaging[]
    """
    for entry in payload.get("entry", []):
        for event in entry.get("messaging", []):
            if _is_echo_or_self_message(event):
                continue

            message = event.get("message") or {}
            text = _extract_text_from_message(message)

            if not text:
                continue

            sender_id = _safe_str(event.get("sender", {}).get("id"))
            recipient_id = _safe_str(event.get("recipient", {}).get("id"))
            mid = _safe_str(message.get("mid"))

            if not sender_id:
                continue

            return NormalizedMessage(
                platform="instagram",
                sender_id=sender_id,
                recipient_id=recipient_id,
                message_id=mid or None,
                user_message=text,
                raw_payload=payload,
            )

    return None


def _parse_meta_payload(payload: dict[str, Any]) -> Optional[NormalizedMessage]:
    """
    Parse Meta webhook payload into a single NormalizedMessage.
    Order matters a bit:
    1) Instagram changes-style
    2) Instagram/Facebook messaging-style
    3) fallback by object type
    """
    parsed = _parse_instagram_changes_style(payload)
    if parsed:
        return parsed

    parsed = _parse_instagram_messaging_style(payload)
    if parsed:
        return parsed

    parsed = _parse_facebook(payload)
    if parsed:
        return parsed

    return None


@router.get("/meta", response_class=PlainTextResponse)
async def verify_meta_webhook(request: Request) -> PlainTextResponse:
    mode = request.query_params.get("hub.mode")
    token = request.query_params.get("hub.verify_token")
    challenge = request.query_params.get("hub.challenge", "")

    if mode == "subscribe" and token == settings.meta_verify_token:
        logger.info("Meta webhook verification succeeded.")
        return PlainTextResponse(content=challenge, status_code=status.HTTP_200_OK)

    logger.warning("Meta webhook verification failed.")
    return PlainTextResponse(content="Verification failed", status_code=status.HTTP_403_FORBIDDEN)


@router.post("/meta")
async def receive_meta_webhook(request: Request) -> Response:
    try:
        payload = await request.json()
    except Exception:
        logger.exception("Failed to decode Meta webhook JSON payload.")
        return JSONResponse(
            status_code=status.HTTP_400_BAD_REQUEST,
            content={"status": "bad_request", "detail": "Invalid JSON payload"},
        )

    parsed_message = _parse_meta_payload(payload)
    if not parsed_message:
        logger.info(
            "Meta webhook received unsupported or non-message payload.",
            extra={"object": payload.get("object")},
        )
        return JSONResponse(
            status_code=status.HTTP_200_OK,
            content={"status": "ignored", "reason": "unsupported_or_non_message_event"},
        )

    logger.info(
        "Meta inbound message received.",
        extra={
            "platform": parsed_message.platform,
            "sender_id": parsed_message.sender_id,
            "message_id": parsed_message.message_id,
        },
    )

    message_processor = getattr(request.app.state, "message_processor", None)
    if message_processor is None:
        logger.error("Message processor is not initialized on app.state.")
        return JSONResponse(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            content={"status": "error", "detail": "Message processor unavailable"},
        )

    try:
        process_result = await message_processor.process(parsed_message)
    except Exception:
        logger.exception("Message processor failed.")
        return JSONResponse(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            content={"status": "error", "detail": "Processing failed"},
        )

    outbound_sent = False
    if isinstance(process_result, dict):
        outbound_sent = bool((process_result.get("outbound_result") or {}).get("sent"))

    logger.info(
        "Meta message processed.",
        extra={
            "platform": parsed_message.platform,
            "sender_id": parsed_message.sender_id,
            "outbound_sent": outbound_sent,
        },
    )

    return JSONResponse(
        status_code=status.HTTP_200_OK,
        content={
            "status": "ok",
            "platform": parsed_message.platform,
            "message_id": parsed_message.message_id,
            "outbound_sent": outbound_sent,
        },
    )

    
curl https://flowly-ai-bot.onrender.com/health

	
